name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black .

  docker:
    runs-on: ubuntu-latest
    steps:
      -

        name: Checkout
        uses: actions/checkout@v5
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #-
        #name: Login to Docker Hub
        #uses: docker/login-action@v3
        #with:
         # username: ${{ secrets.DOCKERHUB_USERNAME }}
         # password: ${{ secrets.DOCKERHUB_TOKEN }}
      #-
       # name: Build and push
       # uses: docker/build-push-action@v6
      #  with:
        #    push: true
         #   tags: user/app:latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test/test_api.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
